version: '3.9'

services:
  app:
    image: node:22-alpine # Replace with your preferred Node.js version or application image
    container_name: indeco_admin
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    build:
      context: .
      args:
        VITE_APP_BASE_API: https://indecovietnam-backend.onrender.com/api/
        VITE_APP_HOMEPAGE: /
    ports:
      - "3000:80" # Expose the app on port 3000 (or replace with the appropriate port)
    environment:
      VITE_APP_BASE_API: https://indecovietnam-backend.onrender.com/api/
      # VITE_APP_BASE_API: "http://localhost:1234/api" # Uncomment for local API
      VITE_APP_HOMEPAGE: /
    
