apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    {{- include "labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type}}
  selector:
    {{- include "selectorLabels" . | nindent 6 }}
  ports:
    {{ range .Values.service.cluster}}
    - protocol: {{.protocol}}
      port: {{ .port }}
      targetPort: {{ .target }}
      name: {{ .name }}
    {{end}}